In [50]:
from sklearn import preprocessing
import pandas as np

In [37]:
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

In [38]:
X = []
Y = []

In [46]:
trainset=pd.read_csv('spam_train.csv')
testset=pd.read_csv('spam_test.csv')

In [47]:
trainset.head()

,Unnamed: 0,A.1,A.2,A.3,A.4,A.5,A.6,A.7,A.8,A.9,...,A.49,A.50,A.51,A.52,A.53,A.54,A.55,A.56,A.57,spam
0,4210,0.00,0.00,1.17,0.0,0.00,0.00,0.0,0.00,0.00,...,0.000,0.284,0.0,0.284,0.213,0.071,1.565,12,72,email
1,4311,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00,...,3.024,0.059,0.0,0.059,0.000,0.237,5.016,43,311,email
2,1316,0.27,0.27,0.55,0.0,0.27,0.27,0.0,1.39,0.27,...,0.000,0.279,0.0,2.001,0.093,0.000,3.706,63,341,spam
3,3819,0.00,0.00,0.00,0.0,0.67,0.00,0.0,0.00,0.00,...,0.117,0.117,0.0,0.000,0.000,0.000,1.222,5,33,email
4,2951,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00,...,0.000,0.000,0.0,0.000,0.000,0.000,1.250,2,10,email

In [48]:
testset.head()

,Unnamed: 0,A.1,A.2,A.3,A.4,A.5,A.6,A.7,A.8,A.9,...,A.49,A.50,A.51,A.52,A.53,A.54,A.55,A.56,A.57,spam
0,3,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,...,0.01,0.143,0.0,0.276,0.184,0.01,9.821,485,2259,spam
1,4,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,...,0.00,0.137,0.0,0.137,0.000,0.00,3.537,40,191,spam
2,10,0.06,0.12,0.77,0.0,0.19,0.32,0.38,0.00,0.06,...,0.04,0.030,0.0,0.244,0.081,0.00,1.729,43,749,spam
3,13,0.00,0.69,0.34,0.0,0.34,0.00,0.00,0.00,0.00,...,0.00,0.056,0.0,0.786,0.000,0.00,3.728,61,261,spam
4,21,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,...,0.00,0.729,0.0,0.729,0.000,0.00,3.833,9,23,spam

In [55]:
import numpy as np
X = np.array(X)
Y = np.array(Y)

In [56]:
# the first 2500 out of 3000 emails will serve as training data
X_train = X[0:2500]
Y_train = Y[0:2500]

In [57]:
# the rest 500 emails will serve as testing data
X_test = X[2500:]
y_test = Y[2500:]

In [58]:
X = X_train
y = Y_train

In [63]:
# we have 3 layers: input layer, hidden layer and output layer
# input layer has 57 nodes (1 for each feature)
# hidden layer has 4 nodes
# output layer has 1 node
dim1 = len(X_train)
dim2 = 4

In [65]:
# randomly initialize the weight vectors
np.random.seed(1)
weight0 = 2 * np.random.random((dim1, dim2))-1
weight1 = 2 * np.random.random((dim2, 1))-1

In [67]:
# you can change the number of iterations
for j in range(25000):
    # first evaluate the output for each training email
    layer_0 = X_train
    layer_1 = sigmoid(np.dot(layer_0,weight0))
    layer_2 = sigmoid(np.dot(layer_1,weight1))

In [69]:
# calculate the error
    layer_2_error = Y_train-layer_2

In [70]:
# perform back propagation
    layer_2_delta = layer_2_error * derivative(layer_2)
    layer_1_error = layer_2_delta.dot(weight1.T)
    layer_1_delta = layer_1_error * derivative(layer_1)

ValueError: shapes (0,) and (1,4) not aligned: 0 (dim 0) != 1 (dim 0)